//
// Generated by JTB 1.3.2
//

package syntaxtree;

import javax.swing.tree.DefaultMutableTreeNode;

/**
 * Grammar production:
 * f0 -> <ID>
 * f1 -> <ASIGNATION>
 * f2 -> Exp()
 * f3 -> ( <TERNARY> Exp() <ALTERNATIVE> Exp() )?
 */
public class Asignation implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Exp f2;
   public NodeOptional f3;

   public Asignation(NodeToken n0, NodeToken n1, Exp n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Asignation(NodeToken n0, Exp n1, NodeOptional n2) {
      f0 = n0;
      f1 = new NodeToken("=");
      f2 = n1;
      f3 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public void accept(visitor.Visitor v, DefaultMutableTreeNode parent) {
      v.visit(this, parent);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

