//
// Generated by JTB 1.3.2
//

package syntaxtree;

import javax.swing.tree.DefaultMutableTreeNode;

/**
 * Grammar production:
 * f0 -> <IF>
 * f1 -> <PAR1>
 * f2 -> Exp()
 * f3 -> <PAR2>
 * f4 -> <KEY1>
 * f5 -> ( Sentencia() )*
 * f6 -> <KEY2>
 * f7 -> ( <ELSEIF> <PAR1> Exp() <PAR2> <KEY1> ( Sentencia() )* <KEY2> )?
 * f8 -> ( <ELSE> <KEY1> ( Sentencia() )* <KEY2> )?
 */
public class Sent_if implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Exp f2;
   public NodeToken f3;
   public NodeToken f4;
   public NodeListOptional f5;
   public NodeToken f6;
   public NodeOptional f7;
   public NodeOptional f8;

   public Sent_if(NodeToken n0, NodeToken n1, Exp n2, NodeToken n3, NodeToken n4, NodeListOptional n5, NodeToken n6, NodeOptional n7, NodeOptional n8) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
   }

   public Sent_if(Exp n0, NodeListOptional n1, NodeOptional n2, NodeOptional n3) {
      f0 = new NodeToken("si");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = new NodeToken(")");
      f4 = new NodeToken("{");
      f5 = n1;
      f6 = new NodeToken("}");
      f7 = n2;
      f8 = n3;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public void accept(visitor.Visitor v, DefaultMutableTreeNode parent) {
      v.visit(this, parent);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

